# Generated by Django 3.0.2 on 2020-01-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_item_title', models.CharField(max_length=100)),
                ('education_item_start_date', models.DateField(auto_now=True)),
                ('education_item_end_date', models.DateField(auto_now=True)),
                ('education_item_institution', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
