# Generated by Django 3.0.2 on 2020-01-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_workitem_workitembullet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workitem',
            old_name='work_item_title',
            new_name='work_item_position_title',
        ),
        migrations.AddField(
            model_name='educationitem',
            name='education_item_level',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workitem',
            name='work_item_department',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workitembullet',
            name='work_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.WorkItem'),
        ),
    ]
