# Generated by Django 3.0.2 on 2020-01-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20200108_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationitem',
            name='education_item_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='educationitem',
            name='education_item_start_date',
            field=models.DateField(),
        ),
    ]
