# Generated by Django 3.0.2 on 2020-01-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20200108_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='work_item_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='work_item_start_date',
            field=models.DateField(),
        ),
    ]
