# Generated by Django 3.0.2 on 2020-01-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20200108_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitembullet',
            name='work_item_bullet',
            field=models.TextField(),
        ),
    ]
