# Generated by Django 3.0.2 on 2020-01-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20200108_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitembullet',
            name='work_item_finished',
            field=models.BooleanField(default=False),
        ),
    ]
