# Generated by Django 3.0.2 on 2020-01-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_auto_20200108_2318'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workitembullet',
            constraint=models.UniqueConstraint(fields=('work_item_ordering', 'work_item_finished'), name='ordering constraint'),
        ),
        migrations.AddConstraint(
            model_name='workitembullet',
            constraint=models.UniqueConstraint(fields=('work_item', 'work_item_bullet', 'work_item_finished'), name='duplicate bullet constraint'),
        ),
    ]
